In [1]:
import tensorflow as tf

### Operation type
- element-wise
    - +-*/
- matrix-wise
    - @, matmul
- dim-wise
    - reduce_mean/max/min/sum

In [3]:
# tf.math.log tf.experimental
a = tf.ones([2, 2])
tf.math.log(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [4]:
tf.exp(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.7182817, 2.7182817],
       [2.7182817, 2.7182817]], dtype=float32)>

In [6]:
# @matmul
a = tf.ones([4, 2, 3])
b = tf.fill([4, 3, 5], 2.)
a@b
tf.matmul(a, b)

<tf.Tensor: shape=(4, 2, 5), dtype=float32, numpy=
array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]], dtype=float32)>

#### Recap
- y = w * x + b
- Y = X@W + b
- 标量的形式决定了运算的规则