In [2]:
import tensorflow as tf

##### Basic indexing
- Same with Numpy
- [idx, idx, ...] \
- start:end \
- start:end:step

In [3]:
a = tf.ones([1, 5, 5, 3])
a[0][0] # 取[0][0]个元素

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [4]:
a[0][0][0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

### Numpy-stytle indexing

In [7]:
a = tf.random.normal([4, 28, 28, 3])

a[1].shape

TensorShape([28, 28, 3])

In [9]:
a[1, 2].shape

TensorShape([28, 3])

In [11]:
a[1, 2, 3].shape

TensorShape([3])

In [12]:
a[1, 2, 3, 2].shape

TensorShape([])

start:end, 包前不包后

In [13]:
a = tf.range(10)
a[-1:]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([9])>

In [14]:
a[:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1])>

In [15]:
a[:-1]

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

Indexing by ::
- start:end:step
- ::step

- ...

In [19]:
a = tf.random.normal([2, 3, 2, 3])
# ... 任意长的列表
a[0, ...].shape

TensorShape([3, 2, 3])

### Selective index
- tf.gather
- tf.gather_nd
- tf.boolean_mask

In [20]:
a = tf.random.normal([4, 35, 8])
tf.gather(a, axis=0, indices=[2, 3]).shape

TensorShape([2, 35, 8])

In [21]:
a[2:4].shape

TensorShape([2, 35, 8])

In [22]:
tf.gather(a, axis=0, indices=[2, 1, 4, 0]).shape

TensorShape([4, 35, 8])

In [23]:
tf.gather(a, axis=1, indices=[2, 3, 7, 9, 16]).shape

TensorShape([4, 5, 8])

In [24]:
tf.gather(a, axis=2, indices=[2, 3, 7]).shape

TensorShape([4, 35, 3])