In [28]:
import tensorflow as tf
import numpy as np
import keras
from keras import layers

In [5]:
# from numpy, list
# 直接从numpy创建一个tensor
tf.convert_to_tensor(np.ones([2, 3]), dtype=float)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [6]:
# tf.zeros
# 新建全为某种数值的方法
tf.zeros([])  # tf.zeros([1, 2])这里是把[1, 2]理解为一个shape

# 这里面传入的全部都是shape
tf.zeros([1])
tf.zeros([2, 2])
tf.zeros([2, 3, 3])

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [10]:
# zeros_like, 根据你传进来的一个tensor来创建一个形状一样的tensor，但是数值全部都是zeros
a = tf.zeros([2, 3, 3])
tf.zeros_like(a)

# 等同于下面这个写法,通用的
tf.zeros(a.shape)

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [11]:
# 初始化全部为1
tf.ones(1)
tf.ones([])
tf.ones([2])
tf.ones([2, 3])

# 相当于tf.ones(a.shape)
tf.ones_like(a)

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [13]:
# 对于wx+b这种线性回归问题，一般来说会把w全部初始化为1，b初始化为0
# 如果都不想，则可以使用fill，填充任意相同值
tf.fill([2, 2], 0)
tf.fill([2, 2], 9)
# 第一个element填初始化的shape，第二个element填初始化的值

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 9],
       [9, 9]])>

In [16]:
# 随机化的初始化
# 正态分布
tf.random.normal([2, 2], mean=1, stddev=1)
tf.random.normal([2, 2])
tf.random.truncated_normal([2, 2], mean=0, stddev=1)

# 均匀分布
tf.random.uniform([2, 2], minval=0, maxval=1)
tf.random.uniform([2, 2], minval=0, maxval=100)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[97.143684 , 78.18048  ],
       [17.299759 ,  6.3827634]], dtype=float32)>

In [19]:
# ig. 实现打散index的功能
idx = tf.range(10)
idx = tf.random.shuffle(idx)

a = tf.random.normal([10, 784])
b = tf.random.uniform([10], maxval=10, dtype=tf.int32)

a = tf.gather(a, idx)
b = tf.gather(b, idx)

In [21]:
# tf.constant, 和tf.convert_to_tensor基本上功能是重合的
tf.constant(1)

tf.constant([1])

tf.constant([1, 2.])

# 用constant设定维度时必须是一致的，
tf.constant([[1, 2.], [3., 1.]])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 1.]], dtype=float32)>

In [22]:
# Typical Dim Data
# 1. Scalar: []  loss = (mse(out, y))
# 2. Vector
# 3. Martrix    input x: [b, vec_dim]
# 4. Tensor     Dim=3,常用于自然语言中间

In [26]:
# e.g. Loss
out = tf.random.uniform([4, 10])
y = tf.range(4)
y = tf.one_hot(y, depth=10)

# 这里keras.losses.MeanSquaredError是一个类而不是一个函数，需要先创建一个实例，然后在使用该实例计算损失
# 1. loss = keras.losses.MeanSquaredError
# 2. loss = loss(y, out)
loss = keras.losses.MeanSquaredError()(y, out)

loss = tf.reduce_mean(loss)


In [30]:
# e.g. Vector

net = layers.Dense(10)
net.build((4, 8))
net.kernel
net.bias

<KerasVariable shape=(10,), dtype=float32, path=dense_1/bias>

In [37]:
# e.g. Matrix
x = tf.random.normal([4, 784])

net = layers.Dense(10)
net.build((4, 784))

net(x).shape
# [4, 10]

net.kernel.shape
# [784, 10]

net.bias.shape
# [10]

TensorShape([10])

In [ ]:
# e.g. Tensor
# x:[b, seq_len, word_dim]
(X_train, y_train), (X_test, y_test) = keras.datasets.imdb.load_data(num_words=10000)
x_train = keras.preprocessing.sequence.pad_sequences(X_train, maxlen=80)
x_train.shape

emb = layers.Embedding(x_train)
emb.shape

out = rnn(emb[:4])
out.shape
# out： TensorShape([4, 256])


In [ ]:
# e.g. dim=4 Tensor 
# Image: [b, h, w, 3]
# future maps: [b, h, w, c]
x = tf.random.normal((4, 32, 32, 3))
net = layers.Conv2D(16, kernel_size=3)
net(x)

In [ ]:
# e.g. dim=5 Tensor
# meta-learning : 把一个数据集分割为多个任务
# [task_b, b, h, w, 3]
